-- PostgreSQL schema + sample data for Item & Purchase Management System
--
-- Setup (database pehle banana padta hai, PostgreSQL mein USE / CREATE DATABASE IF NOT EXISTS nahi hota):
--   psql -U postgres -h 127.0.0.1 -c "CREATE DATABASE item_purchase_db"
--   psql -U postgres -h 127.0.0.1 -d item_purchase_db -f db/schema.sql
-- (npm run db:create && npm run db:setup bhi use kar sakte hain)

CREATE TABLE IF NOT EXISTS item_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  purchase_date DATE NOT NULL,
  stock_available INT NOT NULL DEFAULT 0,
  item_type_id INT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_stock CHECK (stock_available >= 0),
  CONSTRAINT fk_item_type FOREIGN KEY (item_type_id) REFERENCES item_types(id)
);

CREATE TABLE IF NOT EXISTS purchases (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id VARCHAR(20) NOT NULL UNIQUE,
  purchase_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchase_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id INT NOT NULL,
  item_id INT NOT NULL,
  quantity INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_qty CHECK (quantity > 0),
  CONSTRAINT uq_purchase_item UNIQUE (purchase_id, item_id),
  CONSTRAINT fk_pi_purchase FOREIGN KEY (purchase_id) REFERENCES purchases(id),
  CONSTRAINT fk_pi_item FOREIGN KEY (item_id) REFERENCES items(id)
);

-- updated_at automatically maintain karo.
-- MySQL ka "ON UPDATE CURRENT_TIMESTAMP" PostgreSQL mein nahi hota, isliye trigger.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_items_updated_at ON items;
CREATE TRIGGER trg_items_updated_at BEFORE UPDATE ON items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_purchases_updated_at ON purchases;
CREATE TRIGGER trg_purchases_updated_at BEFORE UPDATE ON purchases
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Sample data (explicit ids, taaki item_type_id mapping stable rahe)
INSERT INTO item_types (id, type_name) VALUES
  (1, 'Electronics'), (2, 'Furniture'), (3, 'Clothing'), (4, 'Grocery'), (5, 'Stationery')
ON CONFLICT DO NOTHING;

INSERT INTO items (id, name, purchase_date, stock_available, item_type_id, active) VALUES
  (1, 'Laptop', '2026-08-01', 10, 1, TRUE),
  (2, 'Mouse',  '2026-08-01', 20, 1, TRUE),
  (3, 'Chair',  '2026-08-01', 15, 2, TRUE)
ON CONFLICT DO NOTHING;

-- Explicit ids insert karne ke baad identity sequences sync karo
SELECT setval(pg_get_serial_sequence('item_types', 'id'), (SELECT MAX(id) FROM item_types));
SELECT setval(pg_get_serial_sequence('items', 'id'), (SELECT MAX(id) FROM items));

